In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_excel("Train_dataset.xlsx")

In [3]:
df.columns

Index(['people_ID', 'Region', 'Gender', 'Designation', 'Name', 'Married',
       'Children', 'Occupation', 'Mode_transport', 'cases/1M', 'Deaths/1M',
       'comorbidity', 'Age', 'Coma score', 'Pulmonary score',
       'cardiological pressure', 'Diuresis', 'Platelets', 'HBB', 'd-dimer',
       'Heart rate', 'HDL cholesterol', 'Charlson Index', 'Blood Glucose',
       'Insurance', 'salary', 'FT/month', 'Infect_Prob', 'Class'],
      dtype='object')

In [4]:
possible_factors=['people_ID','Region','Gender','Married','Children','Mode_transport','cases/1M','Deaths/1M','comorbidity','Age','Coma score', 'Pulmonary score',
       'cardiological pressure', 'Diuresis', 'Platelets', 'HBB', 'd-dimer',
       'Heart rate', 'HDL cholesterol', 'Charlson Index', 'Blood Glucose',
       'Insurance', 'salary', 'FT/month']

In [5]:
xtrain=df[possible_factors]
ytrain=df['Class']

In [6]:
import sklearn

In [7]:
from sklearn.feature_selection import SelectKBest

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
for i in range(len(xtrain['Pulmonary score'])):
    xtrain['Pulmonary score'][i]=xtrain['Pulmonary score'][i][1:]

C:\Users\Amrita\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Amrita\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3325: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  exec(code_obj, self.user_global_ns, self.user_ns)

In [10]:
xtrain['Mode_transport'].fillna(xtrain['Mode_transport'].mode()[0], inplace=True)
xtrain['comorbidity'].fillna(xtrain['comorbidity'].mode()[0], inplace=True)
xtrain['Children'].fillna(xtrain['Children'].mode()[0], inplace=True)
xtrain['cardiological pressure'].fillna(xtrain['cardiological pressure'].mode()[0], inplace=True)
xtrain['Diuresis'].fillna(xtrain['Diuresis'].mode()[0], inplace=True)
xtrain['Platelets'].fillna(xtrain['Platelets'].mode()[0], inplace=True)
xtrain['HBB'].fillna(xtrain['HBB'].mode()[0], inplace=True)
xtrain['d-dimer'].fillna(xtrain['d-dimer'].mode()[0], inplace=True)
xtrain['Heart rate'].fillna(xtrain['Heart rate'].mode()[0], inplace=True)
xtrain['HDL cholesterol'].fillna(xtrain['HDL cholesterol'].mode()[0], inplace=True)
xtrain['Insurance'].fillna(xtrain['Insurance'].mode()[0], inplace=True)
xtrain['FT/month'].fillna(xtrain['FT/month'].mode()[0], inplace=True)
xtrain.head()

C:\Users\Amrita\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

,people_ID,Region,Gender,Married,Children,Mode_transport,cases/1M,Deaths/1M,comorbidity,Age,...,Platelets,HBB,d-dimer,Heart rate,HDL cholesterol,Charlson Index,Blood Glucose,Insurance,salary,FT/month
0,1,Bhubaneshwar,Female,YES,1.0,Public,2,0,Hypertension,68,...,154.0,93.0,233.0,82.0,58.0,27,7,3600000.0,1300000,2.0
1,2,Bhubaneshwar,Female,YES,2.0,Walk,2,0,Diabetes,64,...,121.0,56.0,328.0,89.0,68.0,5,6,1600000.0,400000,1.0
2,3,Bhubaneshwar,Female,NO,1.0,Public,2,0,None,19,...,124.0,137.0,213.0,77.0,43.0,40,6,3400000.0,900000,1.0
3,4,Bhubaneshwar,Female,YES,1.0,Car,2,0,Coronary Heart Disease,33,...,98.0,167.0,275.0,64.0,60.0,27,7,700000.0,2300000,1.0
4,5,Bhubaneshwar,Female,NO,2.0,Car,2,0,Diabetes,23,...,21.0,153.0,331.0,71.0,64.0,32,7,3200000.0,1100000,1.0

In [11]:
xtrain.set_index('people_ID')

,Region,Gender,Married,Children,Mode_transport,cases/1M,Deaths/1M,comorbidity,Age,Coma score,...,Platelets,HBB,d-dimer,Heart rate,HDL cholesterol,Charlson Index,Blood Glucose,Insurance,salary,FT/month
people_ID,,,,,,,,,,,,,,,,,,,,,
1,Bhubaneshwar,Female,YES,1.0,Public,2,0,Hypertension,68,8,...,154.0,93.0,233.0,82.0,58.0,27,7,3600000.0,1300000,2.0
2,Bhubaneshwar,Female,YES,2.0,Walk,2,0,Diabetes,64,15,...,121.0,56.0,328.0,89.0,68.0,5,6,1600000.0,400000,1.0
3,Bhubaneshwar,Female,NO,1.0,Public,2,0,None,19,13,...,124.0,137.0,213.0,77.0,43.0,40,6,3400000.0,900000,1.0
4,Bhubaneshwar,Female,YES,1.0,Car,2,0,Coronary Heart Disease,33,9,...,98.0,167.0,275.0,64.0,60.0,27,7,700000.0,2300000,1.0
5,Bhubaneshwar,Female,NO,2.0,Car,2,0,Diabetes,23,7,...,21.0,153.0,331.0,71.0,64.0,32,7,3200000.0,1100000,1.0
6,Bhubaneshwar,Female,YES,1.0,Public,2,0,None,35,9,...,139.0,86.0,216.0,94.0,38.0,5,5,4600000.0,1900000,2.0
7,Bhubaneshwar,Female,YES,2.0,Car,2,0,Coronary Heart Disease,61,3,...,75.0,156.0,311.0,99.0,68.0,23,5,4000000.0,1600000,1.0
8,Bhubaneshwar,Female,YES,1.0,Public,2,0,Diabetes,49,10,...,123.0,179.0,242.0,82.0,59.0,34,3,4100000.0,1200000,0.0
9,Bhubaneshwar,Female,YES,2.0,Public,2,0,Hypertension,44,6,...,125.0,156.0,224.0,60.0,37.0,21,7,4500000.0,900000,0.0
10,Bhubaneshwar,Female,YES,1.0,Public,2,0,None,41,14,...,23.0,178.0,277.0,83.0,58.0,28,4,2200000.0,1400000,2.0
11,Bhubaneshwar,Female,YES,1.0,Public,2,0,None,43,9,...,32.0,24.0,203.0,62.0,51.0,31,4,4200000.0,1100000,0.0
12,Bhubaneshwar,Female,YES,0.0,Car,2,0,Coronary Heart Disease,52,5,...,30.0,66.0,224.0,54.0,68.0,14,5,1000000.0,300000,0.0
13,Bhubaneshwar,Female,NO,2.0,Public,2,0,Diabetes,18,15,...,39.0,174.0,213.0,98.0,43.0,33,3,4000000.0,2300000,2.0
14,Bhubaneshwar,Female,YES,2.0,Public,2,0,Hypertension,52,14,...,17.0,48.0,333.0,99.0,51.0,31,5,3500000.0,2200000,2.0
15,Bhubaneshwar,Female,YES,2.0,Public,2,0,Coronary Heart Disease,36,13,...,125.0,24.0,224.0,60.0,38.0,4,6,2500000.0,800000,1.0
16,Bhubaneshwar,Female,YES,1.0,Walk,2,0,Hypertension,68,11,...,48.0,66.0,348.0,94.0,56.0,15,3,5000000.0,2200000,1.0
17,Bhubaneshwar,Female,YES,2.0,Public,2,0,Coronary Heart Disease,55,11,...,150.0,113.0,306.0,53.0,43.0,17,6,4700000.0,1200000,0.0
18,Bhubaneshwar,Female,YES,0.0,Walk,2,0,Diabetes,53,3,...,123.0,173.0,349.0,74.0,63.0,29,6,300000.0,1700000,1.0
19,Bhubaneshwar,Female,YES,1.0,Public,2,0,Coronary Heart Disease,65,9,...,80.0,177.0,287.0,52.0,66.0,37,4,3900000.0,2300000,0.0
20,Bhubaneshwar,Female,YES,2.0,Public,2,0,Diabetes,50,6,...,89.0,170.0,239.0,57.0,41.0,25,4,1300000.0,800000,0.0
21,Bhubaneshwar,Female,YES,0.0,Car,2,0,None,38,6,...,128.0,133.0,325.0,73.0,36.0,38,3,2100000.0,1600000,1.0
22,Bhubaneshwar,Female,NO,2.0,Public,2,0,None,20,12,...,25.0,32.0,343.0,56.0,40.0,20,5,4000000.0,1400000,2.0
23,Bhubaneshwar,Female,NO,2.0,Public,2,0,None,18,7,...,133.0,194.0,215.0,88.0,50.0,33,5,4100000.0,1700000,0.0
24,Bhubaneshwar,Female,YES,1.0,Car,2,0,Diabetes,31,5,...,25.0,158.0,342.0,97.0,61.0,22,3,3700000.0,1600000,0.0
25,Bhubaneshwar,Female,NO,2.0,Car,2,0,None,20,6,...,58.0,204.0,217.0,79.0,37.0,5,4,4100000.0,1000000,0.0
26,Bhubaneshwar,Female,YES,0.0,Public,2,0,Coronary Heart Disease,51,15,...,158.0,96.0,291.0,95.0,67.0,39,6,3100000.0,2000000,2.0
27,Bhubaneshwar,Female,YES,2.0,Public,2,0,Coronary Heart Disease,53,15,...,139.0,176.0,277.0,61.0,59.0,32,7,4500000.0,700000,1.0
28,Bhubaneshwar,Female,YES,1.0,Public,2,0,Diabetes,42,15,...,70.0,190.0,339.0,84.0,48.0,2,5,2900000.0,2000000,0.0
29,Bhubaneshwar,Female,YES,2.0,Public,2,0,Coronary Heart Disease,60,8,...,151.0,42.0,200.0,74.0,46.0,8,7,4000000.0,800000,1.0
30,Bhubaneshwar,Female,YES,1.0,Car,2,0,Coronary Heart Disease,48,3,...,156.0,176.0,284.0,76.0,59.0,0,6,800000.0,1400000,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22666,Bengaluru,Male,YES,0.0,Walk,8,2,None,54,5,...,97.0,101.0,226.0,61.0,43.0,31,3,4500000.0,1500000,0.0
22667,Bengaluru,Male,YES,2.0,Car,8,2,None,30,10,...,123.0,111.0,317.0,90.0,36.0,29,5,3200000.0,800000,1.0
22668,Bengaluru,Male,YES,0.0,Public,8,2,Coronary Heart Disease,40,6,...,43.0,29.0,303.0,53.0,68.0,27,6,400000.0,1300000,1.0
22669,Bengaluru,Male,YES,0.0,Public,8,2,Diabetes,42,6,...,21.0,79.0,322.0,88.0,39.0,19,3,2500000.0,1800000,1.0
22670,Bengaluru,Male,YES,2.0,Car,8,2,Diabetes,35,13,...,125.0,159.0,224.0,60.0,39.0,12,5,4500000.0,400000,1.0
22671,Bengaluru,Male,YES,1.0,Car,8,2,Coronary Heart Disease,61,13,...,99.0,194.0,343.0,80.0,63.0,10,7,2800000.0,1800000,2.0
22672,Bengaluru,Male,NO,2.0,Car,8,2,None,21,14,...,33.0,64.0,320.0,94.0,42.0,36,7,4000000.0,1300000,2.0
22673,Bengaluru,Male,YES,1.0,Public,8,2,None,65,5,...,18.0,38.0,226.0,79.0,49.0,13,4,4800000.0,2000000,2.0
22674,Bengaluru,Male,YES,0.0,Car,8,2,Coronary Heart Disease,36,3,...,117.0,175.0,320.0,95.0,66.0,1,4,2200000.0,1100000,1.0
22675,Bengaluru,Male,NO,2.0,Public,8,2,Coronary Heart Disease,19,4,...,115.0,117.0,328.0,82.0,59.0,23,5,3400000.0,1900000,0.0
22676,Bengaluru,Male,YES,0.0,Walk,8,2,Coronary Heart Disease,47,6,...,19.0,161.0,259.0,55.0,54.0,37,5,4300000.0,700000,2.0
22677,Bengaluru,Male,YES,0.0,Walk,8,2,Diabetes,58,3,...,115.0,43.0,258.0,93.0,50.0,13,3,1000000.0,500000,1.0
22678,Bengaluru,Male,YES,1.0,Walk,8,2,Diabetes,31,15,...,45.0,121.0,342.0,66.0,63.0,37,6,2300000.0,1500000,2.0
22679,Bengaluru,Male,YES,2.0,Public,8,2,Diabetes,66,4,...,146.0,150.0,235.0,95.0,39.0,1,5,700000.0,300000,1.0
22680,Bengaluru,Male,NO,1.0,Car,8,2,None,21,8,...,86.0,154.0,268.0,84.0,35.0,2,4,2200000.0,1300000,0.0
22681,Bengaluru,Male,YES,2.0,Public,8,2,Hypertension,56,8,...,45.0,114.0,349.0,76.0,52.0,3,4,4800000.0,1600000,1.0
22682,Bengaluru,Male,YES,1.0,Walk,8,2,Hypertension,36,4,...,50.0,134.0,343.0,78.0,54.0,24,6,1400000.0,1000000,0.0
22683,Bengaluru,Male,YES,0.0,Public,8,2,Hypertension,50,12,...,42.0,55.0,274.0,96.0,40.0,37,6,700000.0,300000,2.0
22684,Bengaluru,Male,YES,1.0,Car,8,2,Coronary Heart Disease,67,8,...,90.0,92.0,234.0,76.0,44.0,31,7,300000.0,1800000,2.0
22685,Bengaluru,Male,YES,2.0,Public,8,2,Coronary Heart Disease,28,13,...,121.0,93.0,205.0,67.0,67.0,6,7,3600000.0,2100000,1.0
22686,Bengaluru,Male,YES,2.0,Walk,8,2,None,28,9,...,146.0,72.0,307.0,60.0,58.0,35,4,4400000.0,700000,0.0
22687,Bengaluru,Male,YES,2.0,Public,8,2,Hypertension,63,10,...,29.0,98.0,226.0,89.0,39.0,13,7,3400000.0,900000,1.0
22688,Bengaluru,Male,YES,2.0,Public,8,2,Hypertension,63,5,...,53.0,77.0,258.0,67.0,63.0,1,4,4900000.0,1900000,2.0
22689,Bengaluru,Male,NO,2.0,Car,8,2,None,17,3,...,107.0,33.0,271.0,67.0,68.0,38,3,4000000.0,1100000,2.0
22690,Bengaluru,Male,YES,1.0,Public,8,2,Diabetes,35,11,...,78.0,150.0,337.0,69.0,44.0,31,3,3300000.0,1400000,2.0
22691,Bengaluru,Male,NO,2.0,Car,8,2,Diabetes,20,14,...,67.0,24.0,209.0,61.0,56.0,35,7,4000000.0,300000,0.0
22692,Bengaluru,Male,YES,0.0,Car,8,2,None,42,4,...,102.0,134.0,211.0,65.0,47.0,35,7,1500000.0,700000,1.0
22693,Bengaluru,Male,YES,0.0,Public,8,2,Diabetes,59,3,...,111.0,151.0,296.0,87.0,37.0,16,5,3000000.0,2100000,2.0
22694,Bengaluru,Male,YES,1.0,Walk,8,2,Coronary Heart Disease,49,6,...,140.0,110.0,253.0,56.0,70.0,28,5,2900000.0,700000,1.0
22695,Bengaluru,Male,NO,2.0,Car,8,2,Diabetes,17,7,...,65.0,134.0,201.0,82.0,60.0,4,3,2100000.0,1400000,0.0

In [12]:
from sklearn.compose import ColumnTransformer
columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1,2,3,5,8,12])], remainder='passthrough')
xtrain = pd.DataFrame(columnTransformer.fit_transform(xtrain), dtype = np.str)

In [13]:
from sklearn.feature_selection import chi2,f_classif

In [79]:
bestfeatures = SelectKBest(f_classif,k='all')
fit=bestfeatures.fit(xtrain,ytrain)
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(xtrain.columns)
dfpvalues=pd.DataFrame(fit.pvalues_)
ytrain=pd.DataFrame(ytrain)
featureScores = pd.concat([dfcolumns,dfscores,dfpvalues],axis=1)
featureScores.columns = ['Specs','Score','Pvalues']
Xtrain=xtrain[featureScores[featureScores['Pvalues']<.2]['Specs']]
#print(featureScores.sort_values('Score'))
Xtrain.shape

(10714, 23)

In [15]:
pip install xgboost

Requirement already satisfied: xgboost in c:\users\amrita\anaconda3\lib\site-packages (1.0.2)
Requirement already satisfied: scipy in c:\users\amrita\anaconda3\lib\site-packages (from xgboost) (1.2.1)
Requirement already satisfied: numpy in c:\users\amrita\anaconda3\lib\site-packages (from xgboost) (1.16.4)
Note: you may need to restart the kernel to use updated packages.

In [16]:
from keras.callbacks import ModelCheckpoint
from keras.models import Sequential
from keras.layers import Dense, Activation, Flatten
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error 
from matplotlib import pyplot as plt
import seaborn as sb
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
warnings.filterwarnings('ignore', category=DeprecationWarning)
from xgboost import XGBRegressor

Using TensorFlow backend.

In [80]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
train_X, val_X, train_y, val_y = train_test_split(Xtrain,ytrain, test_size = 0.25, random_state = 14)
print(val_y)
from sklearn.ensemble import RandomForestClassifier

# Create the model with 100 trees
model = RandomForestClassifier(n_estimators=100, 
                               bootstrap = True,
                               max_features = 'sqrt')
# Fit on training data
model.fit(train, train_labels)
model = RandomForestRegressor()

model.fit(train_X,train_y)

# Get the mean absolute error on the validation data
predicted_prices = model.predict(val_X)
print(predicted_prices)
MAE = mean_absolute_error(val_y , predicted_prices)
acc =accuracy_score(val_y , predicted_prices)
print('Random forest validation MAE = ', acc)

Random forest validation acc =  0.9029488615154908

In [61]:
df=pd.read_excel("Test_dataset.xlsx")
xtest=df[possible_factors]
for i in range(len(xtest['Pulmonary score'])):
    xtest['Pulmonary score'][i]=xtest['Pulmonary score'][i][1:]

In [62]:
xtest = pd.DataFrame(columnTransformer.fit_transform(xtest), dtype = np.str)
Xtest=xtest[featureScores[featureScores['Pvalues']<.2]['Specs']]
Xtest.shape

(14498, 27)

In [76]:
def make_submission(prediction, sub_name):
    my_submission = pd.DataFrame({'Infection prb':prediction*100})
    #print(my_submission[my_submission>100])
    #my_submission.replace(my_submission[my_submission>100],97.632)
    my_submission.to_csv('{}.csv'.format(sub_name),index=False)
    print('A submission file has been made')

predictions = model.predict_proba(Xtest)
print(predictions)
make_submission(predictions[:,1],'submission(NN2).csv')

[[0.4  0.6 ]
 [0.41 0.59]
 [0.4  0.6 ]
 ...
 [0.49 0.51]
 [0.53 0.47]
 [0.48 0.52]]
A submission file has been made